# Generated by Django 4.1.3 on 2022-12-01 21:32

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to=api.models.Profile.get_file_path, verbose_name='Fotografia')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Celular')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Mechanic')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
