# Generated by Django 4.1.3 on 2022-12-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
